### ISSUE TITLE
additionalProperties:false not working

### ISSUE THREAD

**Issue by myyellowshoe** [mbroadst/thinkagain#2]
Hello there.
Great package btw. I enjoy json schema much better than the standard thinky schema lang.
I want to make sure additional properties can't be set in the db, when saving new data. I noticed you used json schema validation for this, so I've tried using the additionalProperties flag without much luck. I can still add properties that are not defined in the schema.
Shouldn't the following work?

```
var Subscriptions = thinkagain.thinky.createModel('subscriptions', {
    type:"object",
    "additionalProperties":false,
    properties:{
    ...
    } 
   }
```

**Comment by mbroadst** [comment]
@myyellowshoe hm interesting, do you have a more complete test case exhibiting the problem? We do have a test using `additionalProperties: false`, and I use it locally as well, so maybe there's just an issue with configuration?

**Comment by mbroadst** [comment]
@myyellowshoe for instance I added this little test and it passes:
```
it('Model.save should throw a validation error on extra properties', function() {
  let Model = test.thinkagain.createModel(test.table(1), {
    type: 'object',
    additionalProperties: false,
    properties: { id: { type: 'string' } }
  });

  return expect(Model.save({ id: 'foo', bar: 'buzz' }))
    .to.be.rejectedWith(Errors.ValidationError);
});
```

**Comment by myyellowshoe** [comment]
@mbroadst Yeah your completely right. I was all on me for this.

I was doing something like:
```
            var subscriptionInsert = new DB.Subscriptions({
              editing:false,
              foo: bar //Not in schema
            });

            var newSubscription = await subscriptionInsert.save();
```

This was allowed, and didn't realize it was incorrect syntax.
 When it should of been:

```
           var newSubscription = await DB.Subscriptions({
              editing:false,
              foo: bar // Not in schema
            }).save();
```

So all is well now, and this works great.
Appreciate your time on this :)
